In [4]:
  import numpy as np

In [23]:
l=[x for x in range(25)]

In [24]:
x=np.array(l)

In [25]:
x.resize(5,5)

In [26]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
#Q swap rows 

In [27]:
x[[0,1]]=x[[1,0]]

In [28]:
x

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
a=np.arange(25).reshape(5,5)

In [30]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
a[:2,:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
#reverse
a[1::-1,:]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [34]:
a[:2,:]=a[1::-1,:]

In [35]:
a

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
#Q2

In [54]:
vec=np.arange(6).reshape(1,6)

In [55]:
vec

array([[0, 1, 2, 3, 4, 5]])

In [56]:
vec.shape

(1, 6)

In [57]:
vec.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [58]:
vec.shape

(1, 6)

In [59]:
#Q3

In [75]:
x=np.random.randint(3, size=(5, 5))#range =3

In [71]:
y=np.random.randint(3, size=(5, 5))

In [72]:
x

array([[0, 1, 0, 1, 0],
       [1, 0, 2, 0, 2],
       [2, 0, 2, 2, 0],
       [2, 1, 1, 2, 2],
       [2, 2, 2, 0, 2]])

In [73]:
y

array([[0, 0, 2, 0, 1],
       [0, 1, 2, 2, 2],
       [2, 1, 1, 1, 1],
       [1, 2, 0, 2, 2],
       [2, 1, 0, 2, 2]])

In [77]:
x==y#comapre two matrices

array([[False,  True,  True,  True, False],
       [ True, False,  True, False, False],
       [ True,  True, False, False,  True],
       [ True, False, False,  True, False],
       [False,  True,  True, False,  True]])

In [81]:
z=x==y

In [82]:
z*1

array([[0, 1, 1, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 1, 0, 0, 1],
       [1, 0, 0, 1, 0],
       [0, 1, 1, 0, 1]])

In [86]:
#b[x==y]=1

In [87]:
#Q4 [3 4 3 4 0 3 2 4 1 0]

In [95]:
x=len(n)
max_value=max(n)

In [101]:
np.zeros((x,max_value))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
n=[3,4,3,4,0,3,2,4,1,0]

In [110]:
np.eye(5)[n]

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [111]:
x=np.eye(5)[n]

In [119]:
y=np.argmax(x,axis=1)  

In [120]:
y

array([3, 4, 3, 4, 0, 3, 2, 4, 1, 0], dtype=int64)

In [124]:
#z zeros matrix
#z[range(10),a]=1 part1

In [128]:
#Q5 closest to 0.5

In [141]:
np.random.seed(10)
a=np.random.rand(10,3)
print(a)

[[0.77132064 0.02075195 0.63364823]
 [0.74880388 0.49850701 0.22479665]
 [0.19806286 0.76053071 0.16911084]
 [0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096]
 [0.61252607 0.72175532 0.29187607]
 [0.91777412 0.71457578 0.54254437]
 [0.14217005 0.37334076 0.67413362]
 [0.44183317 0.43401399 0.61776698]
 [0.51313824 0.65039718 0.60103895]]


In [142]:
a-0.5

array([[ 0.27132064, -0.47924805,  0.13364823],
       [ 0.24880388, -0.00149299, -0.27520335],
       [-0.30193714,  0.26053071, -0.33088916],
       [-0.41166019,  0.18535982,  0.45339335],
       [-0.49605173,  0.01219226,  0.31262096],
       [ 0.11252607,  0.22175532, -0.20812393],
       [ 0.41777412,  0.21457578,  0.04254437],
       [-0.35782995, -0.12665924,  0.17413362],
       [-0.05816683, -0.06598601,  0.11776698],
       [ 0.01313824,  0.15039718,  0.10103895]])

In [144]:
abs(a-0.5)

array([[0.27132064, 0.47924805, 0.13364823],
       [0.24880388, 0.00149299, 0.27520335],
       [0.30193714, 0.26053071, 0.33088916],
       [0.41166019, 0.18535982, 0.45339335],
       [0.49605173, 0.01219226, 0.31262096],
       [0.11252607, 0.22175532, 0.20812393],
       [0.41777412, 0.21457578, 0.04254437],
       [0.35782995, 0.12665924, 0.17413362],
       [0.05816683, 0.06598601, 0.11776698],
       [0.01313824, 0.15039718, 0.10103895]])

In [146]:
t=abs(a-0.5)

In [148]:
t.min(axis=1)

array([0.13364823, 0.00149299, 0.26053071, 0.18535982, 0.01219226,
       0.11252607, 0.04254437, 0.12665924, 0.05816683, 0.01313824])

In [138]:
y=t.min(axis=1)

In [139]:
y+0.5

array([0.63364823, 0.50149299, 0.76053071, 0.68535982, 0.51219226,
       0.61252607, 0.54254437, 0.62665924, 0.55816683, 0.51313824])

In [153]:
b=a[range(10),np.abs(a-0.5).argmin(axis=1)].reshape(10,1)

In [154]:
b

array([[0.63364823],
       [0.49850701],
       [0.76053071],
       [0.68535982],
       [0.51219226],
       [0.61252607],
       [0.54254437],
       [0.37334076],
       [0.44183317],
       [0.51313824]])

In [155]:
import pandas as pd

In [21]:
df=pd.read_csv('../Data/u.user',sep='|')

In [159]:
df.head()

user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [160]:
df.columns

Index(['user_id', 'age', 'gender', 'occupation', 'zip_code'], dtype='object')

In [161]:
df.shape

(943, 5)

In [162]:
df.index

RangeIndex(start=0, stop=943, step=1)

In [163]:
df.head(20)

user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660

In [164]:
df.tail()

user_id  age gender     occupation zip_code
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

In [165]:
df.dtypes

user_id        int64
age            int64
gender        object
occupation    object
zip_code      object
dtype: object

In [166]:
df['gender']

0      M
1      F
2      M
3      M
4      F
5      M
6      M
7      M
8      M
9      M
10     F
11     F
12     M
13     M
14     F
15     M
16     M
17     F
18     M
19     F
20     M
21     M
22     F
23     F
24     M
25     M
26     F
27     M
28     M
29     M
      ..
913    F
914    M
915    M
916    F
917    M
918    M
919    F
920    F
921    F
922    M
923    M
924    F
925    M
926    M
927    M
928    M
929    F
930    M
931    M
932    M
933    M
934    M
935    M
936    M
937    F
938    F
939    M
940    M
941    F
942    M
Name: gender, Length: 943, dtype: object

In [168]:
df.describe()#only for int ,float

user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

In [169]:
df.gender.value_counts()

M    670
F    273
Name: gender, dtype: int64

In [170]:
#excersie

In [20]:
drinks=pd.read_csv('../Data/drinks.csv')

In [173]:
drinks.head()

country  beer_servings  spirit_servings  wine_servings  \
0  Afghanistan              0                0              0   
1      Albania             89              132             54   
2      Algeria             25                0             14   
3      Andorra            245              138            312   
4       Angola            217               57             45   

   total_litres_of_pure_alcohol continent  
0                           0.0        AS  
1                           4.9        EU  
2                           0.7        AF  
3                          12.4        EU  
4                           5.9        AF

In [174]:
#calculate the mean 'beer_servings'for the entire dataser

In [175]:
drinks.beer_servings.describe()

count    193.000000
mean     106.160622
std      101.143103
min        0.000000
25%       20.000000
50%       76.000000
75%      188.000000
max      376.000000
Name: beer_servings, dtype: float64

In [176]:
df.columns

Index(['user_id', 'age', 'gender', 'occupation', 'zip_code'], dtype='object')

In [178]:
df.occupation.value_counts().head(3)

student     196
other       105
educator     95
Name: occupation, dtype: int64

In [180]:
df.sort_values(by=['age','gender'],ascending=False)#it will sort first age the gender

user_id  age gender     occupation zip_code
480      481   73      M        retired    37771
766      767   70      M       engineer    00000
802      803   70      M  administrator    78212
859      860   70      F        retired    48322
558      559   69      M      executive    10022
584      585   69      M      librarian    98501
348      349   68      M        retired    61455
572      573   68      M        retired    48911
210      211   66      M       salesman    32605
317      318   65      M        retired    06518
563      564   65      M        retired    94591
650      651   65      M        retired    02903
422      423   64      M          other    91606
844      845   64      M         doctor    97405
363      364   63      M       engineer    01810
776      777   63      M     programmer    01810
857      858   63      M       educator    09645
519      520   62      M     healthcare    12603
265      266   62      F  administrator    78756
105      106   61      M        retired    55125
350      351   61      M       educator    49938
933      934   61      M       engineer    22902
89        90   60      M       educator    78155
233      234   60      M        retired    94702
307      308   60      M        retired    95076
463      464   60      M         writer    94583
468      469   60      M       educator    78628
693      694   60      M     programmer    06365
751      752   60      M        retired    21201
899      900   60      M        retired    18505
..       ...  ...    ...            ...      ...
618      619   17      M        student    44134
620      621   17      M        student    60402
699      700   17      M        student    76309
760      761   17      M        student    97302
862      863   17      M        student    60089
340      341   17      F        student    44405
645      646   17      F        student    51250
903      904   17      F        student    61073
56        57   16      M           none    84010
450      451   16      M        student    48446
579      580   16      M        student    17961
433      434   16      F        student    49705
549      550   16      F        student    95453
100      101   15      M        student    05146
178      179   15      M  entertainment    20755
460      461   15      M        student    98102
280      281   15      F        student    06059
617      618   15      F        student    44212
848      849   15      F        student    25652
205      206   14      F        student    53115
812      813   14      F        student    02136
886      887   14      F        student    27249
141      142   13      M          other    48118
627      628   13      M           none    94306
879      880   13      M        student    83702
608      609   13      F        student    55106
673      674   13      F        student    55337
288      289   11      M           none    94619
470      471   10      M        student    77459
29        30    7      M        student    55436

[943 rows x 5 columns]

In [182]:
df.query("age<20")

user_id  age gender     occupation zip_code
29        30    7      M        student    55436
35        36   19      F        student    93117
51        52   18      F        student    55105
56        57   16      M           none    84010
66        67   17      M        student    60402
67        68   19      M        student    22904
100      101   15      M        student    05146
109      110   19      M        student    77840
141      142   13      M          other    48118
178      179   15      M  entertainment    20755
205      206   14      F        student    53115
220      221   19      M        student    20685
222      223   19      F        student    47906
245      246   19      M        student    28734
256      257   17      M        student    77005
257      258   19      F        student    77801
261      262   19      F        student    78264
269      270   18      F        student    63119
280      281   15      F        student    06059
288      289   11      M           none    94619
290      291   19      M        student    44106
302      303   19      M        student    14853
319      320   19      M        student    24060
340      341   17      F        student    44405
346      347   18      M        student    90210
366      367   17      M        student    37411
367      368   18      M        student    92113
374      375   17      M  entertainment    37777
392      393   19      M        student    83686
396      397   17      M        student    27514
..       ...  ...    ...            ...      ...
600      601   19      F         artist    99687
608      609   13      F        student    55106
617      618   15      F        student    44212
618      619   17      M        student    44134
619      620   18      F         writer    81648
620      621   17      M        student    60402
623      624   19      M        student    30067
627      628   13      M           none    94306
630      631   18      F        student    38866
631      632   18      M        student    55454
641      642   18      F        student    95521
645      646   17      F        student    51250
673      674   13      F        student    55337
699      700   17      M        student    76309
709      710   19      M        student    92020
728      729   19      M        student    56567
746      747   19      M          other    93612
760      761   17      M        student    97302
786      787   18      F        student    98620
812      813   14      F        student    02136
816      817   19      M        student    60152
848      849   15      F        student    25652
850      851   18      M          other    29646
858      859   18      F          other    06492
862      863   17      M        student    60089
871      872   19      F        student    74078
879      880   13      M        student    83702
886      887   14      F        student    27249
903      904   17      F        student    61073
924      925   18      F       salesman    49036

[77 rows x 5 columns]

In [187]:
young=df[(df.age<20)&(df.gender=='M')]

In [188]:
young.head()

user_id  age gender occupation zip_code
29        30    7      M    student    55436
56        57   16      M       none    84010
66        67   17      M    student    60402
67        68   19      M    student    22904
100      101   15      M    student    05146

In [191]:
young.occupation.value_counts()

student          37
none              3
other             3
entertainment     2
Name: occupation, dtype: int64

In [193]:
drinks.head()

country  beer_servings  spirit_servings  wine_servings  \
0  Afghanistan              0                0              0   
1      Albania             89              132             54   
2      Algeria             25                0             14   
3      Andorra            245              138            312   
4       Angola            217               57             45   

   total_litres_of_pure_alcohol continent  
0                           0.0        AS  
1                           4.9        EU  
2                           0.7        AF  
3                          12.4        EU  
4                           5.9        AF

In [197]:
drinks[drinks['continent']=='EU']['beer_servings'].describe()

count     45.000000
mean     193.777778
std       99.631569
min        0.000000
25%      127.000000
50%      219.000000
75%      270.000000
max      361.000000
Name: beer_servings, dtype: float64

In [203]:
drinks.sort_values(by=['total_litres_of_pure_alcohol'],ascending=False).head(10)#it will sort first age the gender

country  beer_servings  spirit_servings  wine_servings  \
15              Belarus            142              373             42   
98            Lithuania            343              244             56   
3               Andorra            245              138            312   
68              Grenada            199              438             28   
45       Czech Republic            361              170            134   
61               France            127              151            370   
141  Russian Federation            247              326             73   
81              Ireland            313              118            165   
155            Slovakia            196              293            116   
99           Luxembourg            236              133            271   

     total_litres_of_pure_alcohol continent  
15                           14.4        EU  
98                           12.9        EU  
3                            12.4        EU  
68                           11.9       NaN  
45                           11.8        EU  
61                           11.8        EU  
141                          11.5        AS  
81                           11.4        EU  
155                          11.4        EU  
99                           11.4        EU

In [205]:
#groupby

In [206]:
drinks.groupby('continent').mean()

beer_servings  spirit_servings  wine_servings  \
continent                                                  
AF             61.471698        16.339623      16.264151   
AS             37.045455        60.840909       9.068182   
EU            193.777778       132.555556     142.222222   
OC             89.687500        58.437500      35.625000   
SA            175.083333       114.750000      62.416667   

           total_litres_of_pure_alcohol  
continent                                
AF                             3.007547  
AS                             2.170455  
EU                             8.617778  
OC                             3.381250  
SA                             6.308333

In [207]:
#grp=drinks.groupyby('')

In [209]:
#rename columns
drinks_col=['country','beer','spirit','wine','liters','continent']
drinks.columns=drinks_col

In [210]:
drinks.head()

country  beer  spirit  wine  liters continent
0  Afghanistan     0       0     0     0.0        AS
1      Albania    89     132    54     4.9        EU
2      Algeria    25       0    14     0.7        AF
3      Andorra   245     138   312    12.4        EU
4       Angola   217      57    45     5.9        AF

In [213]:
drinks['mil']=drinks.liters*1000

In [214]:
drinks['mil']

0          0.0
1       4900.0
2        700.0
3      12400.0
4       5900.0
5       4900.0
6       8300.0
7       3800.0
8      10400.0
9       9700.0
10      1300.0
11      6300.0
12      2000.0
13         0.0
14      6300.0
15     14400.0
16     10500.0
17      6800.0
18      1100.0
19       400.0
20      3800.0
21      4600.0
22      5400.0
23      7200.0
24       600.0
25     10300.0
26      4300.0
27      6300.0
28      4000.0
29      4000.0
        ...   
163     5600.0
164     4700.0
165     7200.0
166    10200.0
167     1000.0
168      300.0
169     6400.0
170     3900.0
171      100.0
172     1300.0
173     1100.0
174     6400.0
175     1300.0
176     1400.0
177     2200.0
178     1000.0
179     8300.0
180     8900.0
181     2800.0
182    10400.0
183     5700.0
184     8700.0
185     6600.0
186     2400.0
187      900.0
188     7700.0
189     2000.0
190      100.0
191     2500.0
192     4700.0
Name: mil, Length: 193, dtype: float64

In [215]:
drinks['servings']=drinks.beer+drinks.spirit+drinks.wine

In [216]:
drinks.head()

country  beer  spirit  wine  liters continent      mil  servings
0  Afghanistan     0       0     0     0.0        AS      0.0         0
1      Albania    89     132    54     4.9        EU   4900.0       275
2      Algeria    25       0    14     0.7        AF    700.0        39
3      Andorra   245     138   312    12.4        EU  12400.0       695
4       Angola   217      57    45     5.9        AF   5900.0       319

In [220]:
drinks.drop('mil',axis=1,inplace=True)

In [221]:
drinks[drinks.continent.isnull()]

country  beer  spirit  wine  liters continent  \
5               Antigua & Barbuda   102     128    45     4.9       NaN   
11                        Bahamas   122     176    51     6.3       NaN   
14                       Barbados   143     173    36     6.3       NaN   
17                         Belize   263     114     8     6.8       NaN   
32                         Canada   240     122   100     8.2       NaN   
41                     Costa Rica   149      87    11     4.4       NaN   
43                           Cuba    93     137     5     4.2       NaN   
50                       Dominica    52     286    26     6.6       NaN   
51             Dominican Republic   193     147     9     6.2       NaN   
54                    El Salvador    52      69     2     2.2       NaN   
68                        Grenada   199     438    28    11.9       NaN   
69                      Guatemala    53      69     2     2.2       NaN   
73                          Haiti     1     326     1     5.9       NaN   
74                       Honduras    69      98     2     3.0       NaN   
84                        Jamaica    82      97     9     3.4       NaN   
109                        Mexico   238      68     5     5.5       NaN   
122                     Nicaragua    78     118     1     3.5       NaN   
130                        Panama   285     104    18     7.2       NaN   
143             St. Kitts & Nevis   194     205    32     7.7       NaN   
144                     St. Lucia   171     315    71    10.1       NaN   
145  St. Vincent & the Grenadines   120     221    11     6.3       NaN   
174             Trinidad & Tobago   197     156     7     6.4       NaN   
184                           USA   249     158    84     8.7       NaN   

     servings  
5         275  
11        349  
14        352  
17        385  
32        462  
41        247  
43        235  
50        364  
51        349  
54        123  
68        665  
69        124  
73        328  
74        169  
84        188  
109       311  
122       197  
130       407  
143       431  
144       557  
145       352  
174       360  
184       491

In [222]:
drinks.isnull().sum(axis=0)

country       0
beer          0
spirit        0
wine          0
liters        0
continent    23
servings      0
dtype: int64

In [223]:
drinks.continent.value_counts(dropna=True)

AF    53
EU    45
AS    44
OC    16
SA    12
Name: continent, dtype: int64

In [224]:
drinks[drinks.notnull()]

country  beer  spirit  wine  liters continent  servings
0             Afghanistan     0       0     0     0.0        AS         0
1                 Albania    89     132    54     4.9        EU       275
2                 Algeria    25       0    14     0.7        AF        39
3                 Andorra   245     138   312    12.4        EU       695
4                  Angola   217      57    45     5.9        AF       319
5       Antigua & Barbuda   102     128    45     4.9       NaN       275
6               Argentina   193      25   221     8.3        SA       439
7                 Armenia    21     179    11     3.8        EU       211
8               Australia   261      72   212    10.4        OC       545
9                 Austria   279      75   191     9.7        EU       545
10             Azerbaijan    21      46     5     1.3        EU        72
11                Bahamas   122     176    51     6.3       NaN       349
12                Bahrain    42      63     7     2.0        AS       112
13             Bangladesh     0       0     0     0.0        AS         0
14               Barbados   143     173    36     6.3       NaN       352
15                Belarus   142     373    42    14.4        EU       557
16                Belgium   295      84   212    10.5        EU       591
17                 Belize   263     114     8     6.8       NaN       385
18                  Benin    34       4    13     1.1        AF        51
19                 Bhutan    23       0     0     0.4        AS        23
20                Bolivia   167      41     8     3.8        SA       216
21     Bosnia-Herzegovina    76     173     8     4.6        EU       257
22               Botswana   173      35    35     5.4        AF       243
23                 Brazil   245     145    16     7.2        SA       406
24                 Brunei    31       2     1     0.6        AS        34
25               Bulgaria   231     252    94    10.3        EU       577
26           Burkina Faso    25       7     7     4.3        AF        39
27                Burundi    88       0     0     6.3        AF        88
28          Cote d'Ivoire    37       1     7     4.0        AF        45
29             Cabo Verde   144      56    16     4.0        AF       216
..                    ...   ...     ...   ...     ...       ...       ...
163              Suriname   128     178     7     5.6        SA       313
164             Swaziland    90       2     2     4.7        AF        94
165                Sweden   152      60   186     7.2        EU       398
166           Switzerland   185     100   280    10.2        EU       565
167                 Syria     5      35    16     1.0        AS        56
168            Tajikistan     2      15     0     0.3        AS        17
169              Thailand    99     258     1     6.4        AS       358
170             Macedonia   106      27    86     3.9        EU       219
171           Timor-Leste     1       1     4     0.1        AS         6
172                  Togo    36       2    19     1.3        AF        57
173                 Tonga    36      21     5     1.1        OC        62
174     Trinidad & Tobago   197     156     7     6.4       NaN       360
175               Tunisia    51       3    20     1.3        AF        74
176                Turkey    51      22     7     1.4        AS        80
177          Turkmenistan    19      71    32     2.2        AS       122
178                Tuvalu     6      41     9     1.0        OC        56
179                Uganda    45       9     0     8.3        AF        54
180               Ukraine   206     237    45     8.9        EU       488
181  United Arab Emirates    16     135     5     2.8        AS       156
182        United Kingdom   219     126   195    10.4        EU       540
183              Tanzania    36       6     1     5.7        AF        43
184                   USA   249     158    84     8.7       NaN       491
185               Urug

In [225]:
drinks.continent.value_counts(dropna=True)

AF    53
EU    45
AS    44
OC    16
SA    12
Name: continent, dtype: int64

In [226]:
drinks.continent.value_counts(dropna=False)

AF     53
EU     45
AS     44
NaN    23
OC     16
SA     12
Name: continent, dtype: int64

In [6]:
#drinks.dropna().shape

In [7]:
import pandas as pd

In [8]:
ufo=pd.read_csv('../Data/ufo.csv')

In [9]:
ufo.head()

City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [10]:
ufo['Colors Reported'].value_counts()

ORANGE                          5216
RED                             4809
GREEN                           1897
BLUE                            1855
YELLOW                           842
RED ORANGE                       486
RED GREEN                        469
RED BLUE                         445
RED GREEN BLUE                   166
GREEN BLUE                       147
RED YELLOW                       146
ORANGE YELLOW                    137
ORANGE GREEN                      66
ORANGE BLUE                       58
YELLOW GREEN                      53
RED YELLOW BLUE                   36
RED YELLOW GREEN                  35
RED ORANGE YELLOW                 32
YELLOW BLUE                       27
RED YELLOW GREEN BLUE             26
RED ORANGE BLUE                   21
YELLOW GREEN BLUE                 13
ORANGE GREEN BLUE                 13
RED ORANGE GREEN                  12
RED ORANGE GREEN BLUE              8
ORANGE YELLOW GREEN                5
RED ORANGE YELLOW GREEN            4
O

In [14]:
#ufo.query('state=='VA')

In [16]:
ufo[ufo.State=='VA'].City.value_counts().head()

Virginia Beach    110
Richmond           92
Alexandria         48
Roanoke            35
Chesapeake         33
Name: City, dtype: int64

In [17]:
ufo.iloc[10:20]

City Colors Reported Shape Reported State             Time
10      Fontana             NaN          LIGHT    CA  8/15/1937 21:00
11     Waterloo             NaN       FIREBALL    AL   6/1/1939 20:00
12       Belton             RED         SPHERE    SC  6/30/1939 20:00
13       Keokuk             NaN           OVAL    IA    7/7/1939 2:00
14    Ludington             NaN           DISK    MI   6/1/1941 13:00
15  Forest Home             NaN         CIRCLE    CA   7/2/1941 11:30
16  Los Angeles             NaN            NaN    CA   2/25/1942 0:00
17    Hapeville             NaN            NaN    GA   6/1/1942 22:30
18       Oneida             NaN      RECTANGLE    TN   7/15/1942 1:00
19   Bering Sea             RED          OTHER    AK  4/30/1943 23:00

In [18]:
ufo.loc[10:20,'City']

10        Fontana
11       Waterloo
12         Belton
13         Keokuk
14      Ludington
15    Forest Home
16    Los Angeles
17      Hapeville
18         Oneida
19     Bering Sea
20       Nebraska
Name: City, dtype: object

In [23]:
df['is_male']=df.gender.map({'F':0,'M':1})

In [24]:
df.head()

user_id  age gender  occupation zip_code  is_male
0        1   24      M  technician    85711        1
1        2   53      F       other    94043        0
2        3   23      M      writer    32067        1
3        4   24      M  technician    43537        1
4        5   33      F       other    15213        0

In [25]:
ufo.head()

City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [27]:
ufo['Time']=pd.to_datetime(ufo.Time)

In [28]:
ufo.Time.dt.month

0         6
1         6
2         2
3         6
4         4
5         9
6         6
7         7
8        10
9         6
10        8
11        6
12        6
13        7
14        6
15        7
16        2
17        6
18        7
19        4
20        6
21        8
22        8
23       10
24        1
25        1
26        1
27        4
28        6
29        6
         ..
80513     9
80514     9
80515     9
80516     9
80517     9
80518     9
80519     9
80520     9
80521     9
80522     9
80523     9
80524     9
80525     9
80526     9
80527     9
80528     9
80529     9
80530     9
80531     9
80532     9
80533     9
80534     9
80535     9
80536     9
80537     9
80538     9
80539     9
80540     9
80541     9
80542     9
Name: Time, Length: 80543, dtype: int64

In [30]:
ufo[ufo.Time >pd.datetime(2014,1,1)]#data after 2014

City Colors Reported Shape Reported State  \
75177       Clarksville          ORANGE         SPHERE    TN   
75178         Henderson             NaN         SPHERE    NV   
75179             Salem      RED YELLOW          LIGHT    OR   
75180            Waxhaw             NaN           DISK    NC   
75181           El Paso             NaN      FORMATION    TX   
75182       Goose Creek           GREEN          LIGHT    SC   
75183       Albuquerque             RED            EGG    NM   
75184            Austin             NaN          LIGHT    TX   
75185  Colorado Springs             NaN      FORMATION    CO   
75186              Elon             NaN         CIRCLE    NC   
75187      Mt. Pleasant             NaN         CIRCLE    SC   
75188      Rohnert Park             RED         SPHERE    CA   
75189    Spokane Valley             RED      FORMATION    WA   
75190      Jacksonville          ORANGE         CIRCLE    FL   
75191           Deltona             NaN         SPHERE    FL   
75192   Charlottesville             NaN          LIGHT    VA   
75193           Deltona          ORANGE         CIRCLE    FL   
75194          Fairborn          ORANGE          LIGHT    OH   
75195         Livermore             NaN          LIGHT    CA   
75196           Modesto             RED         CIRCLE    CA   
75197      Saint Albans             NaN       TRIANGLE    WV   
75198        Wilmington          ORANGE       TRIANGLE    NC   
75199           Baldwin             NaN       FIREBALL    NY   
75200         Patterson          ORANGE         SPHERE    CA   
75201             Boise          ORANGE          LIGHT    ID   
75202           Burbank          ORANGE         SPHERE    CA   
75203            Corona          ORANGE         CIRCLE    CA   
75204        Greenfield             RED          LIGHT    IN   
75205      Oakland Park            BLUE          FLASH    FL   
75206             Salem             NaN         CIRCLE    OR   
...                 ...             ...            ...   ...   
80513        Manahawkin             NaN         CIRCLE    NJ   
80514       New Bedford             NaN          LIGHT    MA   
80515        Woodbridge             NaN       TRIANGLE    VA   
80516          Glendale             NaN       CYLINDER    CA   
80517           Laconia             NaN          CIGAR    NH   
80518         Langhorne             NaN          OTHER    PA   
80519        Glen Ellyn             RED         CIRCLE    IL   
80520        Waynesburg             NaN          FLASH    PA   
80521  Canal Winchester             NaN       TRIANGLE    OH   
80522          Lawrence          ORANGE          LIGHT    MA   
80523     Ellicott City             NaN          LIGHT    MD   
80524           Olympia             RED          LIGHT    WA   
80525         Iowa City            BLUE          LIGHT    IA   
80526        Marshfield             NaN          LIGHT    MA   
80527           Seattle             NaN        DIAMOND    WA   
80528    North Royalton             RED       TRIANGLE    OH   
80529         Deer Park             NaN          LIGHT    WA   
80530     Glen St. Mary             NaN           DISK    FL   
80531          Abingdon             NaN         CIRCLE    VA   
80532          Lawrence             NaN          LIGHT    MA   
80533         Melbourne             NaN           OVAL    IA   
80534          Burleson             NaN          LIGHT    TX   
80535     Elizabethtown             NaN         CIRCLE    KY   
80536           Wyoming             RED           DISK    PA   
80537            Neligh             NaN         CIRCLE    NE   
80538            Neligh             NaN         CIRCLE    NE   
80539      Uhrichsville             NaN          LIGHT    OH   
80540            Tucson        RED BLUE            NaN    AZ   
80541       Orland park             RED          LIGHT    IL   
80542          Loughman             NaN          LIGHT    FL   

                     Time  
75177 2014-01-01 00:01